// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running a different command. '
        'For more information, please see the docs: '
        'https://firebase.google.com/docs/flutter/setup#configure-your-app',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case Targetplatform.macOS:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for macos - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgCRcvSoGS6UNgEl0vFx3eDX8C930w2gI',
    appId: '1:44474009687:android:0910ec2bf70cf2767f7b12',
    messagingSenderId: '44474009687',
    projectId: 'formidable-feat-466408-r6',
    storageBucket: 'formidable-feat-466408-r6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOll3MpJOjFEbkftpRTTUNF6IkzFRcjNU',
    appId: '1:44474009687:ios:fb27c91bb122212e7f7b12',
    messagingSenderId: '44474009687',
    projectId: 'formidable-feat-466408-r6',
    storageBucket: 'formidable-feat-466408-r6.firebasestorage.app',
    iosBundleId: 'com.sahayak.ui',
  );
}
